---
- name: Déployer K3s Cluster
  hosts: all
  become: yes
  vars:
    master_ip: ""
    node_token: ""

  tasks:

    - name: Installer K3s sur le master
      when: "'k3s_master' in group_names"
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Récupérer l’IP du master
      when: "'k3s_master' in group_names"
      shell: hostname -I | awk '{print $1}'
      register: master_ip_result

    - name: Sauvegarder l’IP du master dans une variable globale
      when: "'k3s_master' in group_names"
      set_fact:
        master_ip: "{{ master_ip_result.stdout }}"

    - name: Récupérer le token du master
      when: "'k3s_master' in group_names"
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: token_result

    - name: Sauvegarder le token du master dans une variable globale
      when: "'k3s_master' in group_names"
      set_fact:
        node_token: "{{ token_result.stdout }}"

    - name: Attendre que le master soit prêt
      when: "'k3s_worker' in group_names"
      wait_for:
        host: "{{ hostvars[groups['k3s_master'][0]].master_ip }}"
        port: 6443
        timeout: 60

    - name: Installer K3s sur le worker
      when: "'k3s_worker' in group_names"
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars[groups['k3s_master'][0]].master_ip }}:6443" \
        K3S_TOKEN="{{ hostvars[groups['k3s_master'][0]].node_token }}" sh -
      args:
        creates: /usr/local/bin/k3s
